name: Run Postman GraphQL API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  newman-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Step 3: Install Newman
      - name: Install Newman
        run: npm install -g newman

      # Step 4: Run Postman Collection
      - name: Run Postman Tests (GraphQL API)
        run: |
          newman run "Dummy Graphql Api automation Postman.postman_collection.json" \
          -e "Dev Env.postman_environment.json" \
          --reporters cli,html \
          --reporter-html-export newman-report.html

      # Step 5: Upload Test Report
      - name: Upload Newman Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: newman-report.html
